// Code generated by MockGen. DO NOT EDIT.
// Source: ../api-client-go/api_apple.go

// Package forestvpn_api_mock is a generated GoMock package.
package forestvpn_api_mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	api_client_go "github.com/forestvpn/api-client-go"
	gomock "github.com/golang/mock/gomock"
)

// MockAppleApi is a mock of AppleApi interface.
type MockAppleApi struct {
	ctrl     *gomock.Controller
	recorder *MockAppleApiMockRecorder
}

// MockAppleApiMockRecorder is the mock recorder for MockAppleApi.
type MockAppleApiMockRecorder struct {
	mock *MockAppleApi
}

// NewMockAppleApi creates a new mock instance.
func NewMockAppleApi(ctrl *gomock.Controller) *MockAppleApi {
	mock := &MockAppleApi{ctrl: ctrl}
	mock.recorder = &MockAppleApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppleApi) EXPECT() *MockAppleApiMockRecorder {
	return m.recorder
}

// VerifyAppStoreReceipt mocks base method.
func (m *MockAppleApi) VerifyAppStoreReceipt(ctx context.Context) api_client_go.ApiVerifyAppStoreReceiptRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAppStoreReceipt", ctx)
	ret0, _ := ret[0].(api_client_go.ApiVerifyAppStoreReceiptRequest)
	return ret0
}

// VerifyAppStoreReceipt indicates an expected call of VerifyAppStoreReceipt.
func (mr *MockAppleApiMockRecorder) VerifyAppStoreReceipt(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAppStoreReceipt", reflect.TypeOf((*MockAppleApi)(nil).VerifyAppStoreReceipt), ctx)
}

// VerifyAppStoreReceiptExecute mocks base method.
func (m *MockAppleApi) VerifyAppStoreReceiptExecute(r api_client_go.ApiVerifyAppStoreReceiptRequest) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAppStoreReceiptExecute", r)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAppStoreReceiptExecute indicates an expected call of VerifyAppStoreReceiptExecute.
func (mr *MockAppleApiMockRecorder) VerifyAppStoreReceiptExecute(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAppStoreReceiptExecute", reflect.TypeOf((*MockAppleApi)(nil).VerifyAppStoreReceiptExecute), r)
}
