kind: pipeline
name: default

volumes:
  - name: deps
    temp: { }

steps:
  - name: deps
    image: golang:1.19
    commands:
      - go get -d -v .
    volumes:
      - name: deps
        path: /go

  - name: build
    image: golang:1.19
    commands:
      - go build -v ./
    volumes:
      - name: deps
        path: /go
    depends_on:
      - deps

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: cicd
      link_names: true
      template: >
        {{#success build.status}}
          The {{ repo.owner }}/{{ repo.name }} build <{{ build.link }}| {{build.number}} ↗> is succeeded! Thanks <@{{build.author}}>
        {{else}}
          The {{ repo.owner }}/{{ repo.name }} build <{{ build.link }}| {{build.number}} ↗> is broken! Blame <@{{build.author}}>
        {{/success}}
    depends_on:
      - build
    when:
      status: [ success, failure ]


