/*
ForestVPN API

ForestVPN - Fast, secure, and modern VPN. It offers Distributed Computing, Crypto Mining, P2P, Ad Blocking, TOR over VPN, 30+ locations, and a free version with unlimited data. 

API version: 2.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forestvpn_api

import (
	"encoding/json"
)

// CreateStripeSetupIntentRequest struct for CreateStripeSetupIntentRequest
type CreateStripeSetupIntentRequest struct {
	ReturnUrl *string `json:"return_url,omitempty"`
}

// NewCreateStripeSetupIntentRequest instantiates a new CreateStripeSetupIntentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStripeSetupIntentRequest() *CreateStripeSetupIntentRequest {
	this := CreateStripeSetupIntentRequest{}
	return &this
}

// NewCreateStripeSetupIntentRequestWithDefaults instantiates a new CreateStripeSetupIntentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStripeSetupIntentRequestWithDefaults() *CreateStripeSetupIntentRequest {
	this := CreateStripeSetupIntentRequest{}
	return &this
}

// GetReturnUrl returns the ReturnUrl field value if set, zero value otherwise.
func (o *CreateStripeSetupIntentRequest) GetReturnUrl() string {
	if o == nil || isNil(o.ReturnUrl) {
		var ret string
		return ret
	}
	return *o.ReturnUrl
}

// GetReturnUrlOk returns a tuple with the ReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStripeSetupIntentRequest) GetReturnUrlOk() (*string, bool) {
	if o == nil || isNil(o.ReturnUrl) {
    return nil, false
	}
	return o.ReturnUrl, true
}

// HasReturnUrl returns a boolean if a field has been set.
func (o *CreateStripeSetupIntentRequest) HasReturnUrl() bool {
	if o != nil && !isNil(o.ReturnUrl) {
		return true
	}

	return false
}

// SetReturnUrl gets a reference to the given string and assigns it to the ReturnUrl field.
func (o *CreateStripeSetupIntentRequest) SetReturnUrl(v string) {
	o.ReturnUrl = &v
}

func (o CreateStripeSetupIntentRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ReturnUrl) {
		toSerialize["return_url"] = o.ReturnUrl
	}
	return json.Marshal(toSerialize)
}

type NullableCreateStripeSetupIntentRequest struct {
	value *CreateStripeSetupIntentRequest
	isSet bool
}

func (v NullableCreateStripeSetupIntentRequest) Get() *CreateStripeSetupIntentRequest {
	return v.value
}

func (v *NullableCreateStripeSetupIntentRequest) Set(val *CreateStripeSetupIntentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStripeSetupIntentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStripeSetupIntentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStripeSetupIntentRequest(val *CreateStripeSetupIntentRequest) *NullableCreateStripeSetupIntentRequest {
	return &NullableCreateStripeSetupIntentRequest{value: val, isSet: true}
}

func (v NullableCreateStripeSetupIntentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStripeSetupIntentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


