/*
ForestVPN API

ForestVPN - Fast, secure, and modern VPN. It offers Distributed Computing, Crypto Mining, P2P, Ad Blocking, TOR over VPN, 30+ locations, and a free version with unlimited data. 

API version: 2.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forestvpn_api

import (
	"encoding/json"
)

// Server struct for Server
type Server struct {
	Host string `json:"host"`
	NetworkServices []NetworkService `json:"network_services"`
}

// NewServer instantiates a new Server object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServer(host string, networkServices []NetworkService) *Server {
	this := Server{}
	this.Host = host
	this.NetworkServices = networkServices
	return &this
}

// NewServerWithDefaults instantiates a new Server object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerWithDefaults() *Server {
	this := Server{}
	return &this
}

// GetHost returns the Host field value
func (o *Server) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *Server) GetHostOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *Server) SetHost(v string) {
	o.Host = v
}

// GetNetworkServices returns the NetworkServices field value
func (o *Server) GetNetworkServices() []NetworkService {
	if o == nil {
		var ret []NetworkService
		return ret
	}

	return o.NetworkServices
}

// GetNetworkServicesOk returns a tuple with the NetworkServices field value
// and a boolean to check if the value has been set.
func (o *Server) GetNetworkServicesOk() ([]NetworkService, bool) {
	if o == nil {
    return nil, false
	}
	return o.NetworkServices, true
}

// SetNetworkServices sets field value
func (o *Server) SetNetworkServices(v []NetworkService) {
	o.NetworkServices = v
}

func (o Server) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["host"] = o.Host
	}
	if true {
		toSerialize["network_services"] = o.NetworkServices
	}
	return json.Marshal(toSerialize)
}

type NullableServer struct {
	value *Server
	isSet bool
}

func (v NullableServer) Get() *Server {
	return v.value
}

func (v *NullableServer) Set(val *Server) {
	v.value = val
	v.isSet = true
}

func (v NullableServer) IsSet() bool {
	return v.isSet
}

func (v *NullableServer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServer(val *Server) *NullableServer {
	return &NullableServer{value: val, isSet: true}
}

func (v NullableServer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


