/*
ForestVPN API

ForestVPN - Fast, secure, and modern VPN. It offers Distributed Computing, Crypto Mining, P2P, Ad Blocking, TOR over VPN, 30+ locations, and a free version with unlimited data. 

API version: 2.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forestvpn_api

import (
	"encoding/json"
)

// checks if the LegacyAuthMigrationToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LegacyAuthMigrationToken{}

// LegacyAuthMigrationToken struct for LegacyAuthMigrationToken
type LegacyAuthMigrationToken struct {
	// Firebase authentication token
	Token string `json:"token"`
}

// NewLegacyAuthMigrationToken instantiates a new LegacyAuthMigrationToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLegacyAuthMigrationToken(token string) *LegacyAuthMigrationToken {
	this := LegacyAuthMigrationToken{}
	this.Token = token
	return &this
}

// NewLegacyAuthMigrationTokenWithDefaults instantiates a new LegacyAuthMigrationToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLegacyAuthMigrationTokenWithDefaults() *LegacyAuthMigrationToken {
	this := LegacyAuthMigrationToken{}
	return &this
}

// GetToken returns the Token field value
func (o *LegacyAuthMigrationToken) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *LegacyAuthMigrationToken) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *LegacyAuthMigrationToken) SetToken(v string) {
	o.Token = v
}

func (o LegacyAuthMigrationToken) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LegacyAuthMigrationToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

type NullableLegacyAuthMigrationToken struct {
	value *LegacyAuthMigrationToken
	isSet bool
}

func (v NullableLegacyAuthMigrationToken) Get() *LegacyAuthMigrationToken {
	return v.value
}

func (v *NullableLegacyAuthMigrationToken) Set(val *LegacyAuthMigrationToken) {
	v.value = val
	v.isSet = true
}

func (v NullableLegacyAuthMigrationToken) IsSet() bool {
	return v.isSet
}

func (v *NullableLegacyAuthMigrationToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLegacyAuthMigrationToken(val *LegacyAuthMigrationToken) *NullableLegacyAuthMigrationToken {
	return &NullableLegacyAuthMigrationToken{value: val, isSet: true}
}

func (v NullableLegacyAuthMigrationToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLegacyAuthMigrationToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


