/*
ForestVPN API

ForestVPN - Fast, secure, and modern VPN. It offers Distributed Computing, Crypto Mining, P2P, Ad Blocking, TOR over VPN, 30+ locations, and a free version with unlimited data. 

API version: 2.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forestvpn_api

import (
	"encoding/json"
)

// PaymentOption struct for PaymentOption
type PaymentOption struct {
	Id string `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
}

// NewPaymentOption instantiates a new PaymentOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentOption(id string, slug string, name string) *PaymentOption {
	this := PaymentOption{}
	this.Id = id
	this.Slug = slug
	this.Name = name
	return &this
}

// NewPaymentOptionWithDefaults instantiates a new PaymentOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentOptionWithDefaults() *PaymentOption {
	this := PaymentOption{}
	return &this
}

// GetId returns the Id field value
func (o *PaymentOption) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PaymentOption) GetIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PaymentOption) SetId(v string) {
	o.Id = v
}

// GetSlug returns the Slug field value
func (o *PaymentOption) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *PaymentOption) GetSlugOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *PaymentOption) SetSlug(v string) {
	o.Slug = v
}

// GetName returns the Name field value
func (o *PaymentOption) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PaymentOption) GetNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PaymentOption) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PaymentOption) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentOption) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PaymentOption) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PaymentOption) SetDescription(v string) {
	o.Description = &v
}

func (o PaymentOption) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["slug"] = o.Slug
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullablePaymentOption struct {
	value *PaymentOption
	isSet bool
}

func (v NullablePaymentOption) Get() *PaymentOption {
	return v.value
}

func (v *NullablePaymentOption) Set(val *PaymentOption) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentOption) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentOption(val *PaymentOption) *NullablePaymentOption {
	return &NullablePaymentOption{value: val, isSet: true}
}

func (v NullablePaymentOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


