/*
ForestVPN API

ForestVPN - Fast, secure, and modern VPN. It offers Distributed Computing, Crypto Mining, P2P, Ad Blocking, TOR over VPN, 30+ locations, and a free version with unlimited data. 

API version: 2.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forestvpn_api

import (
	"encoding/json"
)

// checks if the WireGuardPeerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WireGuardPeerInfo{}

// WireGuardPeerInfo struct for WireGuardPeerInfo
type WireGuardPeerInfo struct {
	PubKey *string `json:"pub_key,omitempty"`
	User *WireGuardPeerUser `json:"user,omitempty"`
	Device *WireGuardPeerDevice `json:"device,omitempty"`
}

// NewWireGuardPeerInfo instantiates a new WireGuardPeerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWireGuardPeerInfo() *WireGuardPeerInfo {
	this := WireGuardPeerInfo{}
	return &this
}

// NewWireGuardPeerInfoWithDefaults instantiates a new WireGuardPeerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWireGuardPeerInfoWithDefaults() *WireGuardPeerInfo {
	this := WireGuardPeerInfo{}
	return &this
}

// GetPubKey returns the PubKey field value if set, zero value otherwise.
func (o *WireGuardPeerInfo) GetPubKey() string {
	if o == nil || isNil(o.PubKey) {
		var ret string
		return ret
	}
	return *o.PubKey
}

// GetPubKeyOk returns a tuple with the PubKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WireGuardPeerInfo) GetPubKeyOk() (*string, bool) {
	if o == nil || isNil(o.PubKey) {
		return nil, false
	}
	return o.PubKey, true
}

// HasPubKey returns a boolean if a field has been set.
func (o *WireGuardPeerInfo) HasPubKey() bool {
	if o != nil && !isNil(o.PubKey) {
		return true
	}

	return false
}

// SetPubKey gets a reference to the given string and assigns it to the PubKey field.
func (o *WireGuardPeerInfo) SetPubKey(v string) {
	o.PubKey = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *WireGuardPeerInfo) GetUser() WireGuardPeerUser {
	if o == nil || isNil(o.User) {
		var ret WireGuardPeerUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WireGuardPeerInfo) GetUserOk() (*WireGuardPeerUser, bool) {
	if o == nil || isNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *WireGuardPeerInfo) HasUser() bool {
	if o != nil && !isNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given WireGuardPeerUser and assigns it to the User field.
func (o *WireGuardPeerInfo) SetUser(v WireGuardPeerUser) {
	o.User = &v
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *WireGuardPeerInfo) GetDevice() WireGuardPeerDevice {
	if o == nil || isNil(o.Device) {
		var ret WireGuardPeerDevice
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WireGuardPeerInfo) GetDeviceOk() (*WireGuardPeerDevice, bool) {
	if o == nil || isNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *WireGuardPeerInfo) HasDevice() bool {
	if o != nil && !isNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given WireGuardPeerDevice and assigns it to the Device field.
func (o *WireGuardPeerInfo) SetDevice(v WireGuardPeerDevice) {
	o.Device = &v
}

func (o WireGuardPeerInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WireGuardPeerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PubKey) {
		toSerialize["pub_key"] = o.PubKey
	}
	if !isNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !isNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	return toSerialize, nil
}

type NullableWireGuardPeerInfo struct {
	value *WireGuardPeerInfo
	isSet bool
}

func (v NullableWireGuardPeerInfo) Get() *WireGuardPeerInfo {
	return v.value
}

func (v *NullableWireGuardPeerInfo) Set(val *WireGuardPeerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableWireGuardPeerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableWireGuardPeerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWireGuardPeerInfo(val *WireGuardPeerInfo) *NullableWireGuardPeerInfo {
	return &NullableWireGuardPeerInfo{value: val, isSet: true}
}

func (v NullableWireGuardPeerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWireGuardPeerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


