/*
ForestVPN API

ForestVPN - Fast, secure, and modern VPN. It offers Distributed Computing, Crypto Mining, P2P, Ad Blocking, TOR over VPN, 30+ locations, and a free version with unlimited data. 

API version: 2.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forestvpn_api

import (
	"encoding/json"
	"time"
)

// AccessTokenRequest struct for AccessTokenRequest
type AccessTokenRequest struct {
	Id string `json:"id"`
	UserAgent *string `json:"user_agent,omitempty"`
	AccessToken *string `json:"access_token,omitempty"`
	Status string `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

// NewAccessTokenRequest instantiates a new AccessTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessTokenRequest(id string, status string, createdAt time.Time, expiresAt time.Time) *AccessTokenRequest {
	this := AccessTokenRequest{}
	this.Id = id
	this.Status = status
	this.CreatedAt = createdAt
	this.ExpiresAt = expiresAt
	return &this
}

// NewAccessTokenRequestWithDefaults instantiates a new AccessTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessTokenRequestWithDefaults() *AccessTokenRequest {
	this := AccessTokenRequest{}
	return &this
}

// GetId returns the Id field value
func (o *AccessTokenRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AccessTokenRequest) GetIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AccessTokenRequest) SetId(v string) {
	o.Id = v
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise.
func (o *AccessTokenRequest) GetUserAgent() string {
	if o == nil || isNil(o.UserAgent) {
		var ret string
		return ret
	}
	return *o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTokenRequest) GetUserAgentOk() (*string, bool) {
	if o == nil || isNil(o.UserAgent) {
    return nil, false
	}
	return o.UserAgent, true
}

// HasUserAgent returns a boolean if a field has been set.
func (o *AccessTokenRequest) HasUserAgent() bool {
	if o != nil && !isNil(o.UserAgent) {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given string and assigns it to the UserAgent field.
func (o *AccessTokenRequest) SetUserAgent(v string) {
	o.UserAgent = &v
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *AccessTokenRequest) GetAccessToken() string {
	if o == nil || isNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTokenRequest) GetAccessTokenOk() (*string, bool) {
	if o == nil || isNil(o.AccessToken) {
    return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *AccessTokenRequest) HasAccessToken() bool {
	if o != nil && !isNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *AccessTokenRequest) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetStatus returns the Status field value
func (o *AccessTokenRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AccessTokenRequest) GetStatusOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AccessTokenRequest) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AccessTokenRequest) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AccessTokenRequest) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
    return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AccessTokenRequest) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *AccessTokenRequest) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *AccessTokenRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *AccessTokenRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

func (o AccessTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.UserAgent) {
		toSerialize["user_agent"] = o.UserAgent
	}
	if !isNil(o.AccessToken) {
		toSerialize["access_token"] = o.AccessToken
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if true {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	return json.Marshal(toSerialize)
}

type NullableAccessTokenRequest struct {
	value *AccessTokenRequest
	isSet bool
}

func (v NullableAccessTokenRequest) Get() *AccessTokenRequest {
	return v.value
}

func (v *NullableAccessTokenRequest) Set(val *AccessTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessTokenRequest(val *AccessTokenRequest) *NullableAccessTokenRequest {
	return &NullableAccessTokenRequest{value: val, isSet: true}
}

func (v NullableAccessTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


