/*
ForestVPN API

ForestVPN - Fast, secure, and modern VPN. It offers Distributed Computing, Crypto Mining, P2P, Ad Blocking, TOR over VPN, 30+ locations, and a free version with unlimited data. 

API version: 2.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forestvpn_api

import (
	"encoding/json"
)

// checks if the TokenObtain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenObtain{}

// TokenObtain struct for TokenObtain
type TokenObtain struct {
	Access string `json:"access"`
	Refresh string `json:"refresh"`
	LoginUrl string `json:"login_url"`
}

// NewTokenObtain instantiates a new TokenObtain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenObtain(access string, refresh string, loginUrl string) *TokenObtain {
	this := TokenObtain{}
	this.Access = access
	this.Refresh = refresh
	this.LoginUrl = loginUrl
	return &this
}

// NewTokenObtainWithDefaults instantiates a new TokenObtain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenObtainWithDefaults() *TokenObtain {
	this := TokenObtain{}
	return &this
}

// GetAccess returns the Access field value
func (o *TokenObtain) GetAccess() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Access
}

// GetAccessOk returns a tuple with the Access field value
// and a boolean to check if the value has been set.
func (o *TokenObtain) GetAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Access, true
}

// SetAccess sets field value
func (o *TokenObtain) SetAccess(v string) {
	o.Access = v
}

// GetRefresh returns the Refresh field value
func (o *TokenObtain) GetRefresh() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Refresh
}

// GetRefreshOk returns a tuple with the Refresh field value
// and a boolean to check if the value has been set.
func (o *TokenObtain) GetRefreshOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Refresh, true
}

// SetRefresh sets field value
func (o *TokenObtain) SetRefresh(v string) {
	o.Refresh = v
}

// GetLoginUrl returns the LoginUrl field value
func (o *TokenObtain) GetLoginUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LoginUrl
}

// GetLoginUrlOk returns a tuple with the LoginUrl field value
// and a boolean to check if the value has been set.
func (o *TokenObtain) GetLoginUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoginUrl, true
}

// SetLoginUrl sets field value
func (o *TokenObtain) SetLoginUrl(v string) {
	o.LoginUrl = v
}

func (o TokenObtain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenObtain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access"] = o.Access
	toSerialize["refresh"] = o.Refresh
	toSerialize["login_url"] = o.LoginUrl
	return toSerialize, nil
}

type NullableTokenObtain struct {
	value *TokenObtain
	isSet bool
}

func (v NullableTokenObtain) Get() *TokenObtain {
	return v.value
}

func (v *NullableTokenObtain) Set(val *TokenObtain) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenObtain) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenObtain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenObtain(val *TokenObtain) *NullableTokenObtain {
	return &NullableTokenObtain{value: val, isSet: true}
}

func (v NullableTokenObtain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenObtain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


