/*
ForestVPN API

ForestVPN defeats content restrictions and censorship to deliver unlimited access to video, music, social media, and more, from anywhere in the world. 

API version: 2.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forestvpn_api

import (
	"encoding/json"
)

// CloudPaymentsAuth struct for CloudPaymentsAuth
type CloudPaymentsAuth struct {
	TransactionId *int32 `json:"transaction_id,omitempty"`
	Secure3d *CloudPaymentsSecure3d `json:"secure3d,omitempty"`
}

// NewCloudPaymentsAuth instantiates a new CloudPaymentsAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudPaymentsAuth() *CloudPaymentsAuth {
	this := CloudPaymentsAuth{}
	return &this
}

// NewCloudPaymentsAuthWithDefaults instantiates a new CloudPaymentsAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudPaymentsAuthWithDefaults() *CloudPaymentsAuth {
	this := CloudPaymentsAuth{}
	return &this
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *CloudPaymentsAuth) GetTransactionId() int32 {
	if o == nil || o.TransactionId == nil {
		var ret int32
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudPaymentsAuth) GetTransactionIdOk() (*int32, bool) {
	if o == nil || o.TransactionId == nil {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *CloudPaymentsAuth) HasTransactionId() bool {
	if o != nil && o.TransactionId != nil {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given int32 and assigns it to the TransactionId field.
func (o *CloudPaymentsAuth) SetTransactionId(v int32) {
	o.TransactionId = &v
}

// GetSecure3d returns the Secure3d field value if set, zero value otherwise.
func (o *CloudPaymentsAuth) GetSecure3d() CloudPaymentsSecure3d {
	if o == nil || o.Secure3d == nil {
		var ret CloudPaymentsSecure3d
		return ret
	}
	return *o.Secure3d
}

// GetSecure3dOk returns a tuple with the Secure3d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudPaymentsAuth) GetSecure3dOk() (*CloudPaymentsSecure3d, bool) {
	if o == nil || o.Secure3d == nil {
		return nil, false
	}
	return o.Secure3d, true
}

// HasSecure3d returns a boolean if a field has been set.
func (o *CloudPaymentsAuth) HasSecure3d() bool {
	if o != nil && o.Secure3d != nil {
		return true
	}

	return false
}

// SetSecure3d gets a reference to the given CloudPaymentsSecure3d and assigns it to the Secure3d field.
func (o *CloudPaymentsAuth) SetSecure3d(v CloudPaymentsSecure3d) {
	o.Secure3d = &v
}

func (o CloudPaymentsAuth) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TransactionId != nil {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if o.Secure3d != nil {
		toSerialize["secure3d"] = o.Secure3d
	}
	return json.Marshal(toSerialize)
}

type NullableCloudPaymentsAuth struct {
	value *CloudPaymentsAuth
	isSet bool
}

func (v NullableCloudPaymentsAuth) Get() *CloudPaymentsAuth {
	return v.value
}

func (v *NullableCloudPaymentsAuth) Set(val *CloudPaymentsAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudPaymentsAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudPaymentsAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudPaymentsAuth(val *CloudPaymentsAuth) *NullableCloudPaymentsAuth {
	return &NullableCloudPaymentsAuth{value: val, isSet: true}
}

func (v NullableCloudPaymentsAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudPaymentsAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


