/*
ForestVPN API

ForestVPN - Fast, secure, and modern VPN. It offers Distributed Computing, Crypto Mining, P2P, Ad Blocking, TOR over VPN, 30+ locations, and a free version with unlimited data. 

API version: 2.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forestvpn_api

import (
	"encoding/json"
)

// checks if the CloudPaymentsPost3ds type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudPaymentsPost3ds{}

// CloudPaymentsPost3ds struct for CloudPaymentsPost3ds
type CloudPaymentsPost3ds struct {
	TransactionId int32 `json:"transactionId"`
}

// NewCloudPaymentsPost3ds instantiates a new CloudPaymentsPost3ds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudPaymentsPost3ds(transactionId int32) *CloudPaymentsPost3ds {
	this := CloudPaymentsPost3ds{}
	this.TransactionId = transactionId
	return &this
}

// NewCloudPaymentsPost3dsWithDefaults instantiates a new CloudPaymentsPost3ds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudPaymentsPost3dsWithDefaults() *CloudPaymentsPost3ds {
	this := CloudPaymentsPost3ds{}
	return &this
}

// GetTransactionId returns the TransactionId field value
func (o *CloudPaymentsPost3ds) GetTransactionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *CloudPaymentsPost3ds) GetTransactionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *CloudPaymentsPost3ds) SetTransactionId(v int32) {
	o.TransactionId = v
}

func (o CloudPaymentsPost3ds) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudPaymentsPost3ds) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transactionId"] = o.TransactionId
	return toSerialize, nil
}

type NullableCloudPaymentsPost3ds struct {
	value *CloudPaymentsPost3ds
	isSet bool
}

func (v NullableCloudPaymentsPost3ds) Get() *CloudPaymentsPost3ds {
	return v.value
}

func (v *NullableCloudPaymentsPost3ds) Set(val *CloudPaymentsPost3ds) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudPaymentsPost3ds) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudPaymentsPost3ds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudPaymentsPost3ds(val *CloudPaymentsPost3ds) *NullableCloudPaymentsPost3ds {
	return &NullableCloudPaymentsPost3ds{value: val, isSet: true}
}

func (v NullableCloudPaymentsPost3ds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudPaymentsPost3ds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


