/*
ForestVPN API

ForestVPN defeats content restrictions and censorship to deliver unlimited access to video, music, social media, and more, from anywhere in the world. 

API version: 2.0
Contact: support@forestvpn.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forestvpn_api

import (
	"encoding/json"
)

// StripePaymentIntent struct for StripePaymentIntent
type StripePaymentIntent struct {
	ClientSecret string `json:"client_secret"`
}

// NewStripePaymentIntent instantiates a new StripePaymentIntent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStripePaymentIntent(clientSecret string) *StripePaymentIntent {
	this := StripePaymentIntent{}
	this.ClientSecret = clientSecret
	return &this
}

// NewStripePaymentIntentWithDefaults instantiates a new StripePaymentIntent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStripePaymentIntentWithDefaults() *StripePaymentIntent {
	this := StripePaymentIntent{}
	return &this
}

// GetClientSecret returns the ClientSecret field value
func (o *StripePaymentIntent) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *StripePaymentIntent) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *StripePaymentIntent) SetClientSecret(v string) {
	o.ClientSecret = v
}

func (o StripePaymentIntent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["client_secret"] = o.ClientSecret
	}
	return json.Marshal(toSerialize)
}

type NullableStripePaymentIntent struct {
	value *StripePaymentIntent
	isSet bool
}

func (v NullableStripePaymentIntent) Get() *StripePaymentIntent {
	return v.value
}

func (v *NullableStripePaymentIntent) Set(val *StripePaymentIntent) {
	v.value = val
	v.isSet = true
}

func (v NullableStripePaymentIntent) IsSet() bool {
	return v.isSet
}

func (v *NullableStripePaymentIntent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStripePaymentIntent(val *StripePaymentIntent) *NullableStripePaymentIntent {
	return &NullableStripePaymentIntent{value: val, isSet: true}
}

func (v NullableStripePaymentIntent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStripePaymentIntent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


